version: "3.8"

services:
  db:
    image: postgres:13.8
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: usdt-rate-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable
      GRINEX_API_BASE: ${GRINEX_API_BASE}
      GRINEX_DEPTH_PATH: ${GRINEX_DEPTH_PATH}
      GRINEX_MARKET: ${GRINEX_MARKET}
      GRPC_PORT: ":${GRPC_PORT}"
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      - db

volumes:
  postgres_data:
